//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex. abc@abc.abc.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English and number only.
        /// </summary>
        public static string EnglishNumberOnly {
            get {
                return ResourceManager.GetString("EnglishNumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English only.
        /// </summary>
        public static string EnglishOnly {
            get {
                return ResourceManager.GetString("EnglishOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate code exists..
        /// </summary>
        public static string ErrorCodeMany {
            get {
                return ResourceManager.GetString("ErrorCodeMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using safe delete mode and you tried to delete a table without a key column.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate email entry..
        /// </summary>
        public static string ErrorEmailMany {
            get {
                return ResourceManager.GetString("ErrorEmailMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors caused by your action. Please read the alert from the system..
        /// </summary>
        public static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate host entry..
        /// </summary>
        public static string ErrorHostMany {
            get {
                return ResourceManager.GetString("ErrorHostMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate name exists..
        /// </summary>
        public static string ErrorMany {
            get {
                return ResourceManager.GetString("ErrorMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Has Occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate type exists..
        /// </summary>
        public static string ErrorTypeMany {
            get {
                return ResourceManager.GetString("ErrorTypeMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate username entry..
        /// </summary>
        public static string ErrorUsernameMany {
            get {
                return ResourceManager.GetString("ErrorUsernameMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำมาใช้.
        /// </summary>
        public static string LabelApply {
            get {
                return ResourceManager.GetString("LabelApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string LabelBus {
            get {
                return ResourceManager.GetString("LabelBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trip.
        /// </summary>
        public static string LabelCreateTrip {
            get {
                return ResourceManager.GetString("LabelCreateTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangkaok, Thailand.
        /// </summary>
        public static string LabelFromDescription {
            get {
                return ResourceManager.GetString("LabelFromDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string LabelFromTitle {
            get {
                return ResourceManager.GetString("LabelFromTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Booking.
        /// </summary>
        public static string LabelMyBooking {
            get {
                return ResourceManager.GetString("LabelMyBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-way.
        /// </summary>
        public static string LabelOneWay {
            get {
                return ResourceManager.GetString("LabelOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Tours.
        /// </summary>
        public static string LabelPackageTours {
            get {
                return ResourceManager.GetString("LabelPackageTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger.
        /// </summary>
        public static string LabelPassenger {
            get {
                return ResourceManager.GetString("LabelPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The beauty of &lt;b&gt;travel is the story&lt;/b&gt; along the way..
        /// </summary>
        public static string LabelPromoMessage {
            get {
                return ResourceManager.GetString("LabelPromoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string LabelPromotion {
            get {
                return ResourceManager.GetString("LabelPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round trip.
        /// </summary>
        public static string LabelRoundTrip {
            get {
                return ResourceManager.GetString("LabelRoundTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangkok, Thailand.
        /// </summary>
        public static string LabelToDescription {
            get {
                return ResourceManager.GetString("LabelToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string LabelToTitle {
            get {
                return ResourceManager.GetString("LabelToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranSportation.
        /// </summary>
        public static string LabelTransportation {
            get {
                return ResourceManager.GetString("LabelTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Insurance.
        /// </summary>
        public static string LabelTravelInSurance {
            get {
                return ResourceManager.GetString("LabelTravelInSurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel type.
        /// </summary>
        public static string LabelTravelType {
            get {
                return ResourceManager.GetString("LabelTravelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number only.
        /// </summary>
        public static string NumberOnly {
            get {
                return ResourceManager.GetString("NumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill {0}..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Maxnimum  {2}  recommended {1} characters..
        /// </summary>
        public static string RequiredMaxLength {
            get {
                return ResourceManager.GetString("RequiredMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Integer Maxnimum  {2}  recommended {1} Value..
        /// </summary>
        public static string RequiredNumeberLength {
            get {
                return ResourceManager.GetString("RequiredNumeberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an image to go with this article. Files must be less then 10 MB. Allowed file types: .png, .jpg.
        /// </summary>
        public static string UploadImageFormat {
            get {
                return ResourceManager.GetString("UploadImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an PDF to go with this article. Files must be less then 10 MB. Allowed file types:.pdf.
        /// </summary>
        public static string UploadPdfFormat {
            get {
                return ResourceManager.GetString("UploadPdfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex. https://www.abcd.com.
        /// </summary>
        public static string UrlFormat {
            get {
                return ResourceManager.GetString("UrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
    }
}
